/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 card.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/card.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SPADES.geometry} material={materials['default']} position={[-3.704, 7.854, -13.054]} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/card.gltf')
