/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 card.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

export function Card(props) {
    const { nodes, materials } = useGLTF("/assets/card/card.gltf");
    const ref = useRef();

    useFrame((state, delta) => {
        ref.current.rotation.x += delta/6 * props.rotationspeed;
        ref.current.rotation.y += delta/4 * props.rotationspeed;
    })

    return (
        <group {...props} dispose={null}>
            <mesh
                ref={ref}
                castShadow
                receiveShadow
                geometry={nodes.SPADES.geometry}
                material={materials["default"]}
                position={[0,0,0]}
                rotation={[-1.249, -1.479, 1.892]}
                scale={0.0095}
            />
        </group>
    );
}

useGLTF.preload("/assets/card/card.gltf");
